abstract public class Car {     // It is the class which contains the abstract methods which are used for standardization.
    // we can inherit this class into the other class.but we must use the override on abstract methods or we need to make that class as an abstract class.
    // as aabstract

    private string Name;
    
    private string Model;
    
    private string price;

    public abstract void run();
    
    
}